<?php

namespace App\Libraries;

/**
 * Countries data with phone codes and ISO codes
 */
class Countries
{
    public static function getAll(): array
    {
        return [
            ['code' => 'DZ', 'name' => 'Algérie (Algeria)', 'phone_code' => '+213', 'region' => 'Africa'],
            ['code' => 'AD', 'name' => 'Andorre (Andorra)', 'phone_code' => '+376', 'region' => 'Europe'],
            ['code' => 'AO', 'name' => 'Angola', 'phone_code' => '+244', 'region' => 'Africa'],
            ['code' => 'AR', 'name' => 'Argentine (Argentina)', 'phone_code' => '+54', 'region' => 'South America'],
            ['code' => 'AM', 'name' => 'Arménie (Armenia)', 'phone_code' => '+374', 'region' => 'Western Asia'],
            ['code' => 'AT', 'name' => 'Autriche (Austria)', 'phone_code' => '+43', 'region' => 'Europe'],
            ['code' => 'AU', 'name' => 'Australie (Australia)', 'phone_code' => '+61', 'region' => 'Oceania'],
            ['code' => 'AZ', 'name' => 'Azerbaïdjan (Azerbaijan)', 'phone_code' => '+994', 'region' => 'Western Asia'],
            ['code' => 'BS', 'name' => 'Bahamas', 'phone_code' => '+1-242', 'region' => 'Caribbean'],
            ['code' => 'BH', 'name' => 'Bahreïn (Bahrain)', 'phone_code' => '+973', 'region' => 'Western Asia'],
            ['code' => 'BD', 'name' => 'Bangladesh', 'phone_code' => '+880', 'region' => 'South Asia'],
            ['code' => 'BB', 'name' => 'Barbade (Barbados)', 'phone_code' => '+1-246', 'region' => 'Caribbean'],
            ['code' => 'BE', 'name' => 'Belgique (Belgium)', 'phone_code' => '+32', 'region' => 'Europe'],
            ['code' => 'BZ', 'name' => 'Belize', 'phone_code' => '+501', 'region' => 'North America'],
            ['code' => 'BJ', 'name' => 'Bénin (Benin)', 'phone_code' => '+229', 'region' => 'Africa'],
            ['code' => 'BT', 'name' => 'Bhoutan (Bhutan)', 'phone_code' => '+975', 'region' => 'South Asia'],
            ['code' => 'BY', 'name' => 'Biélorussie (Belarus)', 'phone_code' => '+375', 'region' => 'Europe'],
            ['code' => 'BO', 'name' => 'Bolivie (Bolivia)', 'phone_code' => '+591', 'region' => 'South America'],
            ['code' => 'BA', 'name' => 'Bosnie-Herzégovine (Bosnia and Herzegovina)', 'phone_code' => '+387', 'region' => 'Europe'],
            ['code' => 'BW', 'name' => 'Botswana', 'phone_code' => '+267', 'region' => 'Africa'],
            ['code' => 'BR', 'name' => 'Brésil (Brazil)', 'phone_code' => '+55', 'region' => 'South America'],
            ['code' => 'GB', 'name' => 'Royaume-Uni (United Kingdom)', 'phone_code' => '+44', 'region' => 'Europe'],
            ['code' => 'BG', 'name' => 'Bulgarie (Bulgaria)', 'phone_code' => '+359', 'region' => 'Europe'],
            ['code' => 'BF', 'name' => 'Burkina Faso', 'phone_code' => '+226', 'region' => 'Africa'],
            ['code' => 'BI', 'name' => 'Burundi', 'phone_code' => '+257', 'region' => 'Africa'],
            ['code' => 'KH', 'name' => 'Cambodge (Cambodia)', 'phone_code' => '+855', 'region' => 'Southeast Asia'],
            ['code' => 'CM', 'name' => 'Cameroun (Cameroon)', 'phone_code' => '+237', 'region' => 'Africa'],
            ['code' => 'CA', 'name' => 'Canada', 'phone_code' => '+1', 'region' => 'North America'],
            ['code' => 'CV', 'name' => 'Cap-Vert (Cape Verde)', 'phone_code' => '+238', 'region' => 'Africa'],
            ['code' => 'CL', 'name' => 'Chili (Chile)', 'phone_code' => '+56', 'region' => 'South America'],
            ['code' => 'CN', 'name' => 'Chine (China)', 'phone_code' => '+86', 'region' => 'East Asia'],
            ['code' => 'CY', 'name' => 'Chypre (Cyprus)', 'phone_code' => '+357', 'region' => 'Europe'],
            ['code' => 'CO', 'name' => 'Colombie (Colombia)', 'phone_code' => '+57', 'region' => 'South America'],
            ['code' => 'KM', 'name' => 'Comores (Comoros)', 'phone_code' => '+269', 'region' => 'Africa'],
            ['code' => 'CG', 'name' => 'Congo (Congo)', 'phone_code' => '+242', 'region' => 'Africa'],
            ['code' => 'KP', 'name' => 'Corée du Nord (North Korea)', 'phone_code' => '+850', 'region' => 'East Asia'],
            ['code' => 'KR', 'name' => 'Corée du Sud (South Korea)', 'phone_code' => '+82', 'region' => 'East Asia'],
            ['code' => 'CR', 'name' => 'Costa Rica', 'phone_code' => '+506', 'region' => 'Central America'],
            ['code' => 'HR', 'name' => 'Croatie (Croatia)', 'phone_code' => '+385', 'region' => 'Europe'],
            ['code' => 'CU', 'name' => 'Cuba', 'phone_code' => '+53', 'region' => 'Caribbean'],
            ['code' => 'DK', 'name' => 'Danemark (Denmark)', 'phone_code' => '+45', 'region' => 'Europe'],
            ['code' => 'DJ', 'name' => 'Djibouti', 'phone_code' => '+253', 'region' => 'Africa'],
            ['code' => 'DM', 'name' => 'Dominique (Dominica)', 'phone_code' => '+1-767', 'region' => 'Caribbean'],
            ['code' => 'EG', 'name' => 'Égypte (Egypt)', 'phone_code' => '+20', 'region' => 'Africa'],
            ['code' => 'AE', 'name' => 'Émirats Arabes Unis (United Arab Emirates)', 'phone_code' => '+971', 'region' => 'Western Asia'],
            ['code' => 'EC', 'name' => 'Équateur (Ecuador)', 'phone_code' => '+593', 'region' => 'South America'],
            ['code' => 'ER', 'name' => 'Érythrée (Eritrea)', 'phone_code' => '+291', 'region' => 'Africa'],
            ['code' => 'ES', 'name' => 'Espagne (Spain)', 'phone_code' => '+34', 'region' => 'Europe'],
            ['code' => 'EE', 'name' => 'Estonie (Estonia)', 'phone_code' => '+372', 'region' => 'Europe'],
            ['code' => 'US', 'name' => 'États-Unis (United States)', 'phone_code' => '+1', 'region' => 'North America'],
            ['code' => 'ET', 'name' => 'Éthiopie (Ethiopia)', 'phone_code' => '+251', 'region' => 'Africa'],
            ['code' => 'FJ', 'name' => 'Fidji (Fiji)', 'phone_code' => '+679', 'region' => 'Oceania'],
            ['code' => 'FI', 'name' => 'Finlande (Finland)', 'phone_code' => '+358', 'region' => 'Europe'],
            ['code' => 'FR', 'name' => 'France', 'phone_code' => '+33', 'region' => 'Europe'],
            ['code' => 'GA', 'name' => 'Gabon', 'phone_code' => '+241', 'region' => 'Africa'],
            ['code' => 'GM', 'name' => 'Gambie (Gambia)', 'phone_code' => '+220', 'region' => 'Africa'],
            ['code' => 'GE', 'name' => 'Géorgie (Georgia)', 'phone_code' => '+995', 'region' => 'Western Asia'],
            ['code' => 'GH', 'name' => 'Ghana', 'phone_code' => '+233', 'region' => 'Africa'],
            ['code' => 'GI', 'name' => 'Gibraltar', 'phone_code' => '+350', 'region' => 'Europe'],
            ['code' => 'GR', 'name' => 'Grèce (Greece)', 'phone_code' => '+30', 'region' => 'Europe'],
            ['code' => 'GD', 'name' => 'Grenade (Grenada)', 'phone_code' => '+1-473', 'region' => 'Caribbean'],
            ['code' => 'GL', 'name' => 'Groenland (Greenland)', 'phone_code' => '+299', 'region' => 'North America'],
            ['code' => 'GP', 'name' => 'Guadeloupe', 'phone_code' => '+590', 'region' => 'Caribbean'],
            ['code' => 'GU', 'name' => 'Guam', 'phone_code' => '+1-671', 'region' => 'Oceania'],
            ['code' => 'GT', 'name' => 'Guatemala', 'phone_code' => '+502', 'region' => 'Central America'],
            ['code' => 'GG', 'name' => 'Guernesey (Guernsey)', 'phone_code' => '+44', 'region' => 'Europe'],
            ['code' => 'GN', 'name' => 'Guinée (Guinea)', 'phone_code' => '+224', 'region' => 'Africa'],
            ['code' => 'GQ', 'name' => 'Guinée Équatoriale (Equatorial Guinea)', 'phone_code' => '+240', 'region' => 'Africa'],
            ['code' => 'GW', 'name' => 'Guinée-Bissau (Guinea-Bissau)', 'phone_code' => '+245', 'region' => 'Africa'],
            ['code' => 'GY', 'name' => 'Guyana', 'phone_code' => '+592', 'region' => 'South America'],
            ['code' => 'HT', 'name' => 'Haïti (Haiti)', 'phone_code' => '+509', 'region' => 'Caribbean'],
            ['code' => 'HN', 'name' => 'Honduras', 'phone_code' => '+504', 'region' => 'Central America'],
            ['code' => 'HK', 'name' => 'Hong Kong', 'phone_code' => '+852', 'region' => 'East Asia'],
            ['code' => 'HU', 'name' => 'Hongrie (Hungary)', 'phone_code' => '+36', 'region' => 'Europe'],
            ['code' => 'IO', 'name' => 'Territoire Britannique de l\'Océan Indien (British Indian Ocean Territory)', 'phone_code' => '+246', 'region' => 'South Asia'],
            ['code' => 'ID', 'name' => 'Indonésie (Indonesia)', 'phone_code' => '+62', 'region' => 'Southeast Asia'],
            ['code' => 'IQ', 'name' => 'Irak (Iraq)', 'phone_code' => '+964', 'region' => 'Western Asia'],
            ['code' => 'IR', 'name' => 'Iran', 'phone_code' => '+98', 'region' => 'Western Asia'],
            ['code' => 'IE', 'name' => 'Irlande (Ireland)', 'phone_code' => '+353', 'region' => 'Europe'],
            ['code' => 'IS', 'name' => 'Islande (Iceland)', 'phone_code' => '+354', 'region' => 'Europe'],
            ['code' => 'IL', 'name' => 'Israël (Israel)', 'phone_code' => '+972', 'region' => 'Western Asia'],
            ['code' => 'IT', 'name' => 'Italie (Italy)', 'phone_code' => '+39', 'region' => 'Europe'],
            ['code' => 'JM', 'name' => 'Jamaïque (Jamaica)', 'phone_code' => '+1-876', 'region' => 'Caribbean'],
            ['code' => 'JP', 'name' => 'Japon (Japan)', 'phone_code' => '+81', 'region' => 'East Asia'],
            ['code' => 'JE', 'name' => 'Jersey', 'phone_code' => '+44', 'region' => 'Europe'],
            ['code' => 'JO', 'name' => 'Jordanie (Jordan)', 'phone_code' => '+962', 'region' => 'Western Asia'],
            ['code' => 'KZ', 'name' => 'Kazakhstan', 'phone_code' => '+7', 'region' => 'Central Asia'],
            ['code' => 'KE', 'name' => 'Kenya', 'phone_code' => '+254', 'region' => 'Africa'],
            ['code' => 'KI', 'name' => 'Kiribati', 'phone_code' => '+686', 'region' => 'Oceania'],
            ['code' => 'KW', 'name' => 'Koweït (Kuwait)', 'phone_code' => '+965', 'region' => 'Western Asia'],
            ['code' => 'KG', 'name' => 'Kirghizistan (Kyrgyzstan)', 'phone_code' => '+996', 'region' => 'Central Asia'],
            ['code' => 'LA', 'name' => 'Laos', 'phone_code' => '+856', 'region' => 'Southeast Asia'],
            ['code' => 'LS', 'name' => 'Lesotho', 'phone_code' => '+266', 'region' => 'Africa'],
            ['code' => 'LV', 'name' => 'Lettonie (Latvia)', 'phone_code' => '+371', 'region' => 'Europe'],
            ['code' => 'LB', 'name' => 'Liban (Lebanon)', 'phone_code' => '+961', 'region' => 'Western Asia'],
            ['code' => 'LR', 'name' => 'Liberia', 'phone_code' => '+231', 'region' => 'Africa'],
            ['code' => 'LY', 'name' => 'Libye (Libya)', 'phone_code' => '+218', 'region' => 'Africa'],
            ['code' => 'LI', 'name' => 'Liechtenstein', 'phone_code' => '+423', 'region' => 'Europe'],
            ['code' => 'LT', 'name' => 'Lituanie (Lithuania)', 'phone_code' => '+370', 'region' => 'Europe'],
            ['code' => 'LU', 'name' => 'Luxembourg', 'phone_code' => '+352', 'region' => 'Europe'],
            ['code' => 'MO', 'name' => 'Macao', 'phone_code' => '+853', 'region' => 'East Asia'],
            ['code' => 'KG', 'name' => 'Macédoine (North Macedonia)', 'phone_code' => '+389', 'region' => 'Europe'],
            ['code' => 'MG', 'name' => 'Madagascar', 'phone_code' => '+261', 'region' => 'Africa'],
            ['code' => 'MY', 'name' => 'Malaisie (Malaysia)', 'phone_code' => '+60', 'region' => 'Southeast Asia'],
            ['code' => 'MW', 'name' => 'Malawi', 'phone_code' => '+265', 'region' => 'Africa'],
            ['code' => 'MV', 'name' => 'Maldives', 'phone_code' => '+960', 'region' => 'South Asia'],
            ['code' => 'ML', 'name' => 'Mali', 'phone_code' => '+223', 'region' => 'Africa'],
            ['code' => 'MT', 'name' => 'Malte (Malta)', 'phone_code' => '+356', 'region' => 'Europe'],
            ['code' => 'MQ', 'name' => 'Martinique', 'phone_code' => '+596', 'region' => 'Caribbean'],
            ['code' => 'MR', 'name' => 'Mauritanie (Mauritania)', 'phone_code' => '+222', 'region' => 'Africa'],
            ['code' => 'MU', 'name' => 'Maurice (Mauritius)', 'phone_code' => '+230', 'region' => 'Africa'],
            ['code' => 'YT', 'name' => 'Mayotte', 'phone_code' => '+262', 'region' => 'Africa'],
            ['code' => 'MX', 'name' => 'Mexique (Mexico)', 'phone_code' => '+52', 'region' => 'North America'],
            ['code' => 'FM', 'name' => 'Micronésie (Micronesia)', 'phone_code' => '+691', 'region' => 'Oceania'],
            ['code' => 'MD', 'name' => 'Moldavie (Moldova)', 'phone_code' => '+373', 'region' => 'Europe'],
            ['code' => 'MC', 'name' => 'Monaco', 'phone_code' => '+377', 'region' => 'Europe'],
            ['code' => 'MN', 'name' => 'Mongolie (Mongolia)', 'phone_code' => '+976', 'region' => 'East Asia'],
            ['code' => 'ME', 'name' => 'Monténégro (Montenegro)', 'phone_code' => '+382', 'region' => 'Europe'],
            ['code' => 'MA', 'name' => 'Maroc (Morocco)', 'phone_code' => '+212', 'region' => 'Africa'],
            ['code' => 'MZ', 'name' => 'Mozambique', 'phone_code' => '+258', 'region' => 'Africa'],
            ['code' => 'MM', 'name' => 'Myanmar', 'phone_code' => '+95', 'region' => 'Southeast Asia'],
            ['code' => 'NA', 'name' => 'Namibie (Namibia)', 'phone_code' => '+264', 'region' => 'Africa'],
            ['code' => 'NR', 'name' => 'Nauru', 'phone_code' => '+674', 'region' => 'Oceania'],
            ['code' => 'NP', 'name' => 'Népal (Nepal)', 'phone_code' => '+977', 'region' => 'South Asia'],
            ['code' => 'NI', 'name' => 'Nicaragua', 'phone_code' => '+505', 'region' => 'Central America'],
            ['code' => 'NE', 'name' => 'Niger', 'phone_code' => '+227', 'region' => 'Africa'],
            ['code' => 'NG', 'name' => 'Nigéria (Nigeria)', 'phone_code' => '+234', 'region' => 'Africa'],
            ['code' => 'NU', 'name' => 'Niue', 'phone_code' => '+683', 'region' => 'Oceania'],
            ['code' => 'NO', 'name' => 'Norvège (Norway)', 'phone_code' => '+47', 'region' => 'Europe'],
            ['code' => 'NZ', 'name' => 'Nouvelle-Zélande (New Zealand)', 'phone_code' => '+64', 'region' => 'Oceania'],
            ['code' => 'OM', 'name' => 'Oman', 'phone_code' => '+968', 'region' => 'Western Asia'],
            ['code' => 'UG', 'name' => 'Ouganda (Uganda)', 'phone_code' => '+256', 'region' => 'Africa'],
            ['code' => 'UZ', 'name' => 'Ouzbékistan (Uzbekistan)', 'phone_code' => '+998', 'region' => 'Central Asia'],
            ['code' => 'PK', 'name' => 'Pakistan', 'phone_code' => '+92', 'region' => 'South Asia'],
            ['code' => 'PW', 'name' => 'Palau', 'phone_code' => '+680', 'region' => 'Oceania'],
            ['code' => 'PS', 'name' => 'Palestine', 'phone_code' => '+970', 'region' => 'Western Asia'],
            ['code' => 'PA', 'name' => 'Panama', 'phone_code' => '+507', 'region' => 'Central America'],
            ['code' => 'PG', 'name' => 'Papouasie-Nouvelle-Guinée (Papua New Guinea)', 'phone_code' => '+675', 'region' => 'Oceania'],
            ['code' => 'PY', 'name' => 'Paraguay', 'phone_code' => '+595', 'region' => 'South America'],
            ['code' => 'NL', 'name' => 'Pays-Bas (Netherlands)', 'phone_code' => '+31', 'region' => 'Europe'],
            ['code' => 'PE', 'name' => 'Pérou (Peru)', 'phone_code' => '+51', 'region' => 'South America'],
            ['code' => 'PH', 'name' => 'Philippines', 'phone_code' => '+63', 'region' => 'Southeast Asia'],
            ['code' => 'PN', 'name' => 'Îles Pitcairn (Pitcairn Islands)', 'phone_code' => '+64', 'region' => 'Oceania'],
            ['code' => 'PL', 'name' => 'Pologne (Poland)', 'phone_code' => '+48', 'region' => 'Europe'],
            ['code' => 'PT', 'name' => 'Portugal', 'phone_code' => '+351', 'region' => 'Europe'],
            ['code' => 'PR', 'name' => 'Porto Rico (Puerto Rico)', 'phone_code' => '+1-787', 'region' => 'Caribbean'],
            ['code' => 'QA', 'name' => 'Qatar', 'phone_code' => '+974', 'region' => 'Western Asia'],
            ['code' => 'RE', 'name' => 'Réunion', 'phone_code' => '+262', 'region' => 'Africa'],
            ['code' => 'RO', 'name' => 'Roumanie (Romania)', 'phone_code' => '+40', 'region' => 'Europe'],
            ['code' => 'RU', 'name' => 'Russie (Russia)', 'phone_code' => '+7', 'region' => 'Europe/Asia'],
            ['code' => 'RW', 'name' => 'Rwanda', 'phone_code' => '+250', 'region' => 'Africa'],
            ['code' => 'BL', 'name' => 'Saint-Barthélemy (Saint Barthélemy)', 'phone_code' => '+590', 'region' => 'Caribbean'],
            ['code' => 'KN', 'name' => 'Saint-Christophe-et-Niévès (Saint Kitts and Nevis)', 'phone_code' => '+1-869', 'region' => 'Caribbean'],
            ['code' => 'LC', 'name' => 'Sainte-Lucie (Saint Lucia)', 'phone_code' => '+1-758', 'region' => 'Caribbean'],
            ['code' => 'MF', 'name' => 'Saint-Martin (Saint Martin)', 'phone_code' => '+590', 'region' => 'Caribbean'],
            ['code' => 'PM', 'name' => 'Saint-Pierre-et-Miquelon (Saint Pierre and Miquelon)', 'phone_code' => '+508', 'region' => 'North America'],
            ['code' => 'VC', 'name' => 'Saint-Vincent-et-les-Grenadines (Saint Vincent and the Grenadines)', 'phone_code' => '+1-784', 'region' => 'Caribbean'],
            ['code' => 'SH', 'name' => 'Sainte-Hélène (Saint Helena)', 'phone_code' => '+290', 'region' => 'Africa'],
            ['code' => 'SM', 'name' => 'Saint-Marin (San Marino)', 'phone_code' => '+378', 'region' => 'Europe'],
            ['code' => 'ST', 'name' => 'São Tomé-et-Príncipe (Sao Tome and Principe)', 'phone_code' => '+239', 'region' => 'Africa'],
            ['code' => 'SA', 'name' => 'Arabie Saoudite (Saudi Arabia)', 'phone_code' => '+966', 'region' => 'Western Asia'],
            ['code' => 'SN', 'name' => 'Sénégal (Senegal)', 'phone_code' => '+221', 'region' => 'Africa'],
            ['code' => 'RS', 'name' => 'Serbie (Serbia)', 'phone_code' => '+381', 'region' => 'Europe'],
            ['code' => 'SC', 'name' => 'Seychelles', 'phone_code' => '+248', 'region' => 'Africa'],
            ['code' => 'SL', 'name' => 'Sierra Leone', 'phone_code' => '+232', 'region' => 'Africa'],
            ['code' => 'SG', 'name' => 'Singapour (Singapore)', 'phone_code' => '+65', 'region' => 'Southeast Asia'],
            ['code' => 'SK', 'name' => 'Slovaquie (Slovakia)', 'phone_code' => '+421', 'region' => 'Europe'],
            ['code' => 'SI', 'name' => 'Slovénie (Slovenia)', 'phone_code' => '+386', 'region' => 'Europe'],
            ['code' => 'SB', 'name' => 'Îles Salomon (Solomon Islands)', 'phone_code' => '+677', 'region' => 'Oceania'],
            ['code' => 'SO', 'name' => 'Somalie (Somalia)', 'phone_code' => '+252', 'region' => 'Africa'],
            ['code' => 'ZA', 'name' => 'Afrique du Sud (South Africa)', 'phone_code' => '+27', 'region' => 'Africa'],
            ['code' => 'SS', 'name' => 'Soudan du Sud (South Sudan)', 'phone_code' => '+211', 'region' => 'Africa'],
            ['code' => 'SD', 'name' => 'Soudan (Sudan)', 'phone_code' => '+249', 'region' => 'Africa'],
            ['code' => 'SE', 'name' => 'Suède (Sweden)', 'phone_code' => '+46', 'region' => 'Europe'],
            ['code' => 'CH', 'name' => 'Suisse (Switzerland)', 'phone_code' => '+41', 'region' => 'Europe'],
            ['code' => 'SR', 'name' => 'Surinam (Suriname)', 'phone_code' => '+597', 'region' => 'South America'],
            ['code' => 'SJ', 'name' => 'Svalbard et Jan Mayen (Svalbard and Jan Mayen)', 'phone_code' => '+47', 'region' => 'Europe'],
            ['code' => 'SY', 'name' => 'Syrie (Syria)', 'phone_code' => '+963', 'region' => 'Western Asia'],
            ['code' => 'SZ', 'name' => 'Eswatini (Swaziland)', 'phone_code' => '+268', 'region' => 'Africa'],
            ['code' => 'TJ', 'name' => 'Tadjikistan (Tajikistan)', 'phone_code' => '+992', 'region' => 'Central Asia'],
            ['code' => 'TW', 'name' => 'Taïwan (Taiwan)', 'phone_code' => '+886', 'region' => 'East Asia'],
            ['code' => 'TZ', 'name' => 'Tanzanie (Tanzania)', 'phone_code' => '+255', 'region' => 'Africa'],
            ['code' => 'TH', 'name' => 'Thaïlande (Thailand)', 'phone_code' => '+66', 'region' => 'Southeast Asia'],
            ['code' => 'TL', 'name' => 'Timor oriental (East Timor)', 'phone_code' => '+670', 'region' => 'Southeast Asia'],
            ['code' => 'TG', 'name' => 'Togo', 'phone_code' => '+228', 'region' => 'Africa'],
            ['code' => 'TK', 'name' => 'Tokelau', 'phone_code' => '+690', 'region' => 'Oceania'],
            ['code' => 'TO', 'name' => 'Tonga', 'phone_code' => '+676', 'region' => 'Oceania'],
            ['code' => 'TT', 'name' => 'Trinité-et-Tobago (Trinidad and Tobago)', 'phone_code' => '+1-868', 'region' => 'Caribbean'],
            ['code' => 'TN', 'name' => 'Tunisie (Tunisia)', 'phone_code' => '+216', 'region' => 'Africa'],
            ['code' => 'TM', 'name' => 'Turkménistan (Turkmenistan)', 'phone_code' => '+993', 'region' => 'Central Asia'],
            ['code' => 'TC', 'name' => 'Îles Turques-et-Caïques (Turks and Caicos Islands)', 'phone_code' => '+1-649', 'region' => 'Caribbean'],
            ['code' => 'TR', 'name' => 'Turquie (Turkey)', 'phone_code' => '+90', 'region' => 'Western Asia'],
            ['code' => 'TV', 'name' => 'Tuvalu', 'phone_code' => '+688', 'region' => 'Oceania'],
            ['code' => 'UA', 'name' => 'Ukraine', 'phone_code' => '+380', 'region' => 'Europe'],
            ['code' => 'VU', 'name' => 'Vanuatu', 'phone_code' => '+678', 'region' => 'Oceania'],
            ['code' => 'VA', 'name' => 'Vatican (Holy See)', 'phone_code' => '+379', 'region' => 'Europe'],
            ['code' => 'VE', 'name' => 'Venezuela', 'phone_code' => '+58', 'region' => 'South America'],
            ['code' => 'VN', 'name' => 'Viêt Nam (Vietnam)', 'phone_code' => '+84', 'region' => 'Southeast Asia'],
            ['code' => 'VG', 'name' => 'Îles Vierges Britanniques (British Virgin Islands)', 'phone_code' => '+1-284', 'region' => 'Caribbean'],
            ['code' => 'VI', 'name' => 'Îles Vierges des États-Unis (U.S. Virgin Islands)', 'phone_code' => '+1-340', 'region' => 'Caribbean'],
            ['code' => 'WF', 'name' => 'Wallis-et-Futuna (Wallis and Futuna)', 'phone_code' => '+681', 'region' => 'Oceania'],
            ['code' => 'WS', 'name' => 'Samoa', 'phone_code' => '+685', 'region' => 'Oceania'],
            ['code' => 'YE', 'name' => 'Yémen (Yemen)', 'phone_code' => '+967', 'region' => 'Western Asia'],
            ['code' => 'ZM', 'name' => 'Zambie (Zambia)', 'phone_code' => '+260', 'region' => 'Africa'],
            ['code' => 'ZW', 'name' => 'Zimbabwe', 'phone_code' => '+263', 'region' => 'Africa'],
        ];
    }

    /**
     * Get country by code
     */
    public static function getByCode(string $code): ?array
    {
        foreach (self::getAll() as $country) {
            if ($country['code'] === strtoupper($code)) {
                return $country;
            }
        }
        return null;
    }

    /**
     * Get list for select dropdown
     */
    public static function getSelectList(): array
    {
        $list = [];
        foreach (self::getAll() as $country) {
            $list[$country['code']] = $country['name'];
        }
        return $list;
    }

    /**
     * Get phone code for country
     */
    public static function getPhoneCode(string $code): ?string
    {
        $country = self::getByCode($code);
        return $country['phone_code'] ?? null;
    }
}
